# Generated by Django 5.1.1 on 2025-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_building_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='funding',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
