databases:
  - name: savana
    plan: free
    databaseName: savana_8bks
    user: yahia

services:
  - type: web
    plan: free
    name: Savana
    runtime: python
    buildCommand: "./build.sh"  
    startCommand: "python -m gunicorn Savana.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: savana
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
