# Generated by Django 5.1.1 on 2024-11-27 15:55

import django.db.models.deletion
import django_countries.fields
import sellers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_address_building_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=100, unique=True)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('status', models.JSONField(default=sellers.models.default_status)),
                ('stripe_verifeid', models.BooleanField(default=False)),
                ('app_verifeid', models.BooleanField(default=False)),
                ('pm_sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.paymentmethod')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='sellers.seller')),
            ],
        ),
    ]
