# Generated by Django 5.1.1 on 2025-05-01 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('users', '0009_address_building_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='stripe_verifeid',
            new_name='stripe_verified',
        ),
        migrations.AlterField(
            model_name='seller',
            name='pm_sub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.paymentmethod'),
        ),
    ]
