# Generated by Django 5.1.1 on 2025-05-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_rename_stripe_verifeid_seller_stripe_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='app_verifeid',
            new_name='PG_verified',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='stripe_verified',
            new_name='app_verified',
        ),
    ]
