# Generated by Django 5.1.1 on 2025-06-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_rename_app_verifeid_seller_pg_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'permissions': [('can_verify_seller', 'Can verify seller')]},
        ),
    ]
