# Generated by Django 5.1.1 on 2025-08-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_seller_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('product_type', models.CharField(choices=[('medicines', 'Medicines'), ('clothes', 'Clothes'), ('tshirt', 'Clothes -> T-Shirt'), ('shoes', 'Shoes'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('books', 'Books'), ('toys', 'Toys'), ('accessories', 'Accessories'), ('sports_clothes', 'Sports -> Clothes'), ('sports_shoes', 'Sports -> Shoes'), ('jewelry', 'Jewelry'), ('beauty', 'Beauty'), ('automotive', 'Automotive'), ('pet_supplies', 'Pet Supplies'), ('home_appliances', 'Home Appliances'), ('generic', 'Generic'), ('smartphone', 'Electronics -> Smartphone'), ('laptop', 'Electronics -> Laptop')], max_length=50)),
                ('has_variations', models.BooleanField(default=False)),
                ('brand_name', models.CharField(choices=[('generic', 'Generic'), ('eva', 'EVA Pharma'), ('global_napi', 'Global Napi Pharma'), ('apex', 'APEX Pharma S.A.E.')], max_length=50)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('bullet_points', models.JSONField(blank=True, default=list, null=True)),
                ('product_details', models.JSONField(default=dict)),
                ('product_variations', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=14, unique=True)),
                ('theme', models.JSONField(blank=True, default=dict, null=True)),
                ('default', models.BooleanField(default=False)),
                ('product_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='sellers.productidentity')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variations', models.JSONField(blank=True, default=dict, null=True)),
                ('product_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='sellers.productidentity')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller')),
            ],
            options={
                'unique_together': {('seller', 'product_identity')},
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='seller', through='sellers.SellerProduct', to='sellers.productidentity'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=50)),
                ('fullfillment_channel', models.CharField(choices=[('FBM', 'Fulfilled by Merchant'), ('FBA', 'Fulfilled by Amazon')], default='FBM', max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sellers.seller')),
                ('PV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sellers.productvariation')),
            ],
            options={
                'unique_together': {('PV', 'seller')},
            },
        ),
    ]
