# Generated by Django 5.1.1 on 2025-10-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_productidentity_seller_draft_data_productvariation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productidentity',
            options={'permissions': [('can_change_status', 'Can Change Status')]},
        ),
    ]
