# Generated by Django 5.1.1 on 2025-10-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_productidentity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
